#Challenge 1 - Steve's Car Showroom


-- 1. What are the details of all cars purchased in the year 2022?
SELECT *
FROM sales 
JOIN cars
	USING(car_id)
WHERE YEAR(purchase_date)=2022;

-- 2. What is the total number of cars sold by each salesperson?
SELECT name, COUNT(sale_id) total_sale
FROM sales 
JOIN salespersons
	USING(salesman_id)
GROUP BY name
ORDER BY total_sale DESC
;

-- 3. What is the total revenue generated by each salesperson?
SELECT name AS SalesPerson, SUM(cost_$) TotalRevenue
FROM cars
JOIN sales
	USING(car_id)
JOIN salespersons 
USING(salesman_id)
GROUP BY SalesPerson
ORDER BY TotalRevenue DESC;

-- 4. What are the details of the cars sold by each salesperson?
SELECT name SalesPerson, make, make, cost_$, purchase_date
FROM sales
JOIN salespersons
	USING(salesman_id)
JOIN cars
	USING(car_id);

-- 5. What is the total revenue generated by each car type?
SELECT type Car_Type, SUM(cost_$) Total_Revenue
FROM cars
GROUP BY type
ORDER BY Total_Revenue DESC
;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?
SELECT *
FROM cars
JOIN sales
	USING(car_id)
JOIN salespersons
	USING(salesman_id)
WHERE YEAR(purchase_date)=2021 AND name='Emily Wong';

-- 7. What is the total revenue generated by the sales of hatchback cars?
SELECT style, SUM(cost_$)
FROM cars
WHERE style='Hatchback'
GROUP BY style;

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
SELECT style, SUM(cost_$) revenue
FROM cars
JOIN sales
	USING(car_id)
WHERE style='SUV' AND YEAR(purchase_date)=2022
GROUP BY style;

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?
SELECT name, city, COUNT(sale_id) total_sale
FROM salespersons
JOIN sales
	USING(salesman_id)
WHERE YEAR(purchase_date)=2023
GROUP BY name, city
ORDER BY total_sale DESC
LIMIT 1;

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?
SELECT name, age, SUM(cost_$) highest_reveneu
FROM salespersons
JOIN sales
	USING(salesman_id)
JOIN cars
	USING(car_id)
WHERE YEAR(purchase_date)=2022
GROUP BY name, age
ORDER BY highest_reveneu DESC
LIMIT 1;

